spring:
  profiles:
    active: mysql
---
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch?serverTimezone=Asia/Seoul
    username: batch
    password: b1234

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

logging:
  level:
    org:
      springframework:
        web: debug