spring:
  profiles:
    active: mysql
---
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch?serverTimezone=Asia/Seoul
    username: batch
    password: b1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}
      enabled: false



